-- Ignore UI file patterns, patch all UI files processed by DXML that are in the game's `ui` gamedata path.
-- Recommended -- all UI XML files may benefit from patching text elements for correct alignment.
-- Note that XML files in the `textures_descr` directory will always be skipped.
FORCE_PATCH_ALL_UI_FILES = true

-- Patterns for loaded XML files to be checked against. Files only need to contain a partial match for patching to be performed.
-- For example, pattern `ui_options` will match `ui_options.xml` but also `ui_options_16.xml`.
UI_FILE_PATTERNS = { "actor_menu", "message_box", "pda", "talk", "ui_inventory", "ui_keybinding", "ui_mcm",
	"ui_mm_main", "ui_mm_faction_select", "ui_mm_load_dlg", "ui_mm_save_dlg", "ui_options",
	"ui_workshop", "ui_mcm", "ui_options" }

-- Ignore `ui_text_parent_element_patterns` and patch all `text` elements found in any context.
-- Not recommended -- not all text elements are in a proper container element.
-- May cause unwanted layout changes, e.g. vertically stacked text in the main menu.
-- Instead, find element to be patched in UI XML files and add its parent tag to `ui_text_parent_element_patterns` set.
FORCE_PATCH_ALL_TEXT_ELEMENTS = false

-- Patterns for parent elements of `text` elements to be patched.
-- Element names only need to contain a partial match for patching to be performed.
-- For example, pattern `button` will match `button`, but also `button_confirm`, `button_cancel`, and others.
UI_TEXT_PARENT_ELEMENT_PATTERNS = { "text", "txt", "button", "btn", "diff", "compare", "cap", "list", "block",
	"caption", "info", "rank", "name", "community", "money", "weight", "price",
	"cost" }

-- Custom value overrides for specific UI files and elements.
-- Allows specifying a qualified selector to be resolved in a given UI file and a value to be set.
-- Supplying a dictionary will assign given values as attributes to the selected element.
UI_CUSTOM_VALUE = {
	["ui_mm_main_16"] = {
		["shniaga_wnd > shniaga > magnifire > y_offset"] = "-8"
	},
	["ui_options_16"] = {
		["btn_accept > text"] = { y = "-1" },
		["btn_reset > text"] = { y = "-1" },
		["btn_default > text"] = { y = "-1" },
		["btn_cancel > text"] = { y = "-1" }
	},
	["ui_mcm_16"] = {
		["btn_accept > text"] = { y = "-1" },
		["btn_reset > text"] = { y = "-1" },
		["btn_default > text"] = { y = "-1" },
		["btn_cancel > text"] = { y = "-1" },
		["elements > btn_list"] = {
			width = "103"
		}
	},
	["ui_mm_faction_select_16"] = {
		["btn_faction > text"] = { y = "-1" },
		["btn_icon > text"] = { y = "-1" },
		["btn_start > text"] = { y = "-1" },
		["btn_random > text"] = { y = "-1" },
		["btn_back > text"] = { y = "-1" },
		["check_reset > texture"] = "ui_inGame2_checkbox"
	},
	["utils_16"] = {
		["item_info > weight"] = {
			y = "20",
			x = "325"
		},
		["item_info > cost"] = {
			y = "-1000"
		},
		["item_info > no_trade"] = {
			y = "-1000",
			width = "0",
			height = "0"
		},
		["item_info > description"] = {
			y = "40"
		},
		["item_info > description > text"] = {
			complex_mode = "1",
			vert_align = "t"
		},
		["stats_box > cap"] = {
			height = "18",
			y = "0",
			x = "15"
		},
		["stats_box > diff"] = {
			height = "18",
			y = "0",
			x = "180"
		},
		["stats_box > prog_txt"] = {
			height = "18",
			y = "0"
		},
		["stats_box > compare"] = {
			height = "18",
			y = "0"
		},
		["stats_box > icon"] = {
			height = "14",
			width = "10",
			y = "2",
			x = "2"
		},
		["ammo_type > cap_ammo_types"] = {
			x = "12",
			width = "52"
		},
		["ammo_type > cap_ammo_used_type"] = {
			x = "58"
		},
		["ammo_type > cap_ammo_types > text"] = {
			complex_mode = "0",
			vert_align = "t",
			color = "ui_gray_3"
		},
		["ammo_type > cap_ammo_used_type > text"] = {
			complex_mode = "0",
			vert_align = "t",
			color = "ui_gray_3"
		}
	},
	["actor_menu_16"] = {
		["wpn_params > cap_ammo_used_type"] = {
			x = "180"
		}
	},
	["ui_inventory_16"] = {
		["player > money"] = {
			y = "120",
			height = "25"
		}
	},
	["ui_items_cook_16"] = {
		["btn_cook > text"] = {
			y = "-2"
		}
	},
	["maingame_pda_msg_16"] = {
		["time_static"] = {
			y = "2",
			vert_align = "t"
		},
		["caption_static"] = {
			y = "0",
			width = "235",
			vert_align = "t"
		},
		["msg_static"] = {
			y = "16",
			width = "285",
			vert_align = "t"
		}
	}
}
