-- Ignore UI file patterns, patch all UI files processed by DXML that are in the game's `ui` gamedata path.
-- Recommended -- all UI XML files may benefit from patching text elements for correct alignment.
-- Note that XML files in the `textures_descr` directory will always be skipped.
FORCE_PATCH_ALL_UI_FILES = true

-- Patterns for loaded XML files to be checked against. Files only need to contain a partial match for patching to be performed.
-- For example, pattern `ui_options` will match `ui_options.xml` but also `ui_options_16.xml`.
UI_FILE_PATTERNS = { "actor_menu", "message_box", "pda", "talk", "ui_inventory", "ui_keybinding", "ui_mcm",
	"ui_mm_main", "ui_mm_faction_select", "ui_mm_load_dlg", "ui_mm_save_dlg", "ui_options",
	"ui_workshop", "ui_mcm", "ui_options" }

-- Ignore `ui_text_parent_element_patterns` and patch all `text` elements found in any context.
-- Not recommended -- not all text elements are in a proper container element.
-- May cause unwanted layout changes, e.g. vertically stacked text in the main menu.
-- Instead, find element to be patched in UI XML files and add its parent tag to `ui_text_parent_element_patterns` set.
FORCE_PATCH_ALL_TEXT_ELEMENTS = false

-- Patterns for parent elements of `text` elements to be patched.
-- Element names only need to contain a partial match for patching to be performed.
-- For example, pattern `button` will match `button`, but also `button_confirm`, `button_cancel`, and others.
UI_TEXT_PARENT_ELEMENT_PATTERNS = { "text", "txt", "button", "btn", "diff", "compare", "cap", "list", "block",
	"caption", "info", "rank", "name", "community", "money", "weight", "price",
	"cost", "filter" }

-- Custom value overrides for specific UI files and elements.
-- Allows specifying a qualified selector to be resolved in a given UI file and a value to be set.
-- Supplying a dictionary will assign given values as attributes to the selected element.
UI_CUSTOM_VALUE = {
	["ui_mm_main_16"] = {
		["shniaga_wnd > shniaga > magnifire > y_offset"] = "-8"
	},
	["ui_options_16"] = {
		["btn_accept > text"] = { y = "-1" },
		["btn_reset > text"] = { y = "-1" },
		["btn_default > text"] = { y = "-1" },
		["btn_cancel > text"] = { y = "-1" }
	},
	["ui_mcm_16"] = {
		["btn_accept > text"] = { y = "-1" },
		["btn_reset > text"] = { y = "-1" },
		["btn_default > text"] = { y = "-1" },
		["btn_cancel > text"] = { y = "-1" },
		["elements > btn_list"] = {
			width = "103"
		}
	},
	["ui_mm_faction_select_16"] = {
		["btn_faction > text"] = { y = "-1" },
		["btn_icon > text"] = { y = "-1" },
		["btn_start > text"] = { y = "-1" },
		["btn_random > text"] = { y = "-1" },
		["btn_back > text"] = { y = "-1" },
		["check_reset > texture"] = "ui_inGame2_checkbox"
	},
	["ui_mm_load_dlg_16"] = {
		["btn_load > text"] = { y = "-1" },
		["btn_delete > text"] = { y = "-1" },
		["btn_cancel > text"] = { y = "-1" }
	},
	["utils_16"] = {
		["item_info > weight"] = {
			y = "20",
			x = "325"
		},
		["item_info > cost"] = {
			y = "-1000"
		},
		["item_info > no_trade"] = {
			y = "-1000",
			width = "0",
			height = "0"
		},
		["item_info > description"] = {
			y = "40"
		},
		["item_info > description > text"] = {
			complex_mode = "1",
			vert_align = "t"
		},
		["stats_box > cap"] = {
			height = "18",
			y = "0",
			x = "15"
		},
		["stats_box > diff"] = {
			height = "18",
			y = "0",
			x = "180"
		},
		["stats_box > prog_txt"] = {
			height = "18",
			y = "0"
		},
		["stats_box > compare"] = {
			height = "18",
			y = "0"
		},
		["stats_box > icon"] = {
			height = "14",
			width = "10",
			y = "2",
			x = "2"
		},
		["ammo_type > cap_ammo_types"] = {
			x = "12",
			width = "52"
		},
		["ammo_type > cap_ammo_used_type"] = {
			x = "58"
		},
		["ammo_type > cap_ammo_types > text"] = {
			complex_mode = "0",
			vert_align = "t",
			color = "ui_gray_3"
		},
		["ammo_type > cap_ammo_used_type > text"] = {
			complex_mode = "0",
			vert_align = "t",
			color = "ui_gray_3"
		}
	},
	["actor_menu_16"] = {
		["wpn_params > cap_ammo_used_type"] = {
			x = "180"
		}
	},
	["ui_inventory_16"] = {
		["player > money"] = {
			y = "120",
			height = "25"
		}
	},
	["ui_items_cook_16"] = {
		["btn_cook > text"] = {
			y = "-2"
		}
	},
	["pda_16"] = {
		-- Backgrounds around tabs
		["background_static"] = {},
		-- "Guide to the Zone" label
		["caption_static"] = {
			y = "17",
			x = "26"
		},
		["caption_static > text"] = {
			complex_mode = "1",
			vert_align = "c"
		},
		-- Clock (Right-side)
		["clock_wnd"] = {
			y = "36"
		},
		["clock_wnd > text"] = {
			complex_mode = "1",
			vert_align = "c"
		},
		["battery_bar"] = {
			y = "29"
		}
	},
	["pda_taskboard_16"] = {
		["btn_refresh_tasks"] = {
			height = "16",
			width = "14",
			y = "100"
		},
		["btn_refresh_tasks > text"] = {
			y = "2",
			x = "20",
			complex_mode = "0"
		}
	},
	["pda_ranking_16"] = {
		["stat_info > stat[y=103]"] = {
			y = "111"
		},
		["stat_info > stat[y=144]"] = {
			y = "148"
		},
		["stat_info > stat[y=179]"] = {
			y = "183"
		},
		["stat_info > stat[y=214]"] = {
			y = "217"
		},
		["stat_info > stat[y=264]"] = {
			y = "265"
		},
		["coc_ranking_itm > name"] = {
			x = "76"
		},
		["coc_ranking_itm > descr"] = {
			x = "76"
		},
		["coc_ranking_itm_actor > name"] = {
			x = "76"
		},
		["coc_ranking_itm_actor > descr"] = {
			x = "76"
		}
	},
	["pda_relations_16"] = {
		["btn_to_text"] = {
			width = "16",
			height = "20",
			y = "102"
		},
		["btn_to_text > text"] = {
			x = "38",
			y = "3",
			complex_mode = "0",
		},
		["tab > caption"] = {
			y = "22"
		},
		["tab > caption > text"] = {
			y = "0"
		},
		["companion_background"] = {
			y = "42"
		},
		["companion_background > text"] = {},
		["auto_check > text"] = {
			x = "-60",
			y = "6",
			align = "l"
		}
	},
	["pda_contacts_16"] = {
		["auto_check"] = {
			y = "95"
		},
		["auto_check > text"] = {
			y = "7",
			complex_mode = "0"
		},
		["show_all"] = {
			y = "95"
		},
		["show_all > text"] = {
			y = "7",
			complex_mode = "0"
		}
	},
	["pda_encyclopedia_16"] = {
		["frame1 > caption"] = {
			y = "95"
		},
		["image_checkbox"] = {
			y = "95"
		},
		["image_checkbox > text"] = {
			y = "7",
			complex_mode = "0"
		},
		["message_checkbox"] = {
			y = "95"
		},
		["message_checkbox > text"] = {
			y = "7",
			complex_mode = "0"
		}
	},
	["pda_radio_16"] = {},
	["pda_logs_16"] = {
		["filter_news"] = {
			y = "95",
		},
		["filter_news > text"] = {
			y = "7",
			complex_mode = "0"
		},
		["filter_talk"] = {
			y = "95",
		},
		["filter_talk > text"] = {
			y = "7",
			complex_mode = "0"
		},
		["period_caption"] = {
			x = "528",
			y = "98"
		},
		["period"] = {
			x = "640",
			y = "98"
		},
		["period > text"] = {
			complex_mode = "1"
		},
		["btn_prev_period"] = {
			width = "16",
			height = "20",
			x = "636",
			y = "100"
		},
		["btn_next_period"] = {
			width = "16",
			height = "20",
			x = "757",
			y = "100"
		},
		["center_caption"] = {
			y = "155"
		},
		["logs_item > date_static"] = {
			y = "0"
		},
		["logs_item > date_static > text"] = {
			complex_mode = "1",
			vert_align = "t"
		},
		["logs_item > caption_static"] = {
			y = "0"
		},
		["logs_item > caption_static > text"] = {
			complex_mode = "1",
			vert_align = "t"
		},
		["logs_item > text_static"] = {
			y = "16"
		},
		["logs_item > text_static > text"] = {
			complex_mode = "1",
			vert_align = "t"
		},
		["logs_item > image"] = {
			y = "0"
		},
	},
	["maingame_pda_msg_16"] = {
		["time_static"] = {
			y = "2",
		},
		["time_static > text"] = {
			vert_align = "t"
		},
		["caption_static"] = {
			y = "2",
			width = "235",
		},
		["caption_static > text"] = {
			vert_align = "t"
		},
		["msg_static"] = {
			y = "16",
			width = "285"
		},
		["msg_static > text"] = {
			vert_align = "t"
		},
	}
}
